version: '2'
services:
  yako_vega:
    build:
      context: ./
    volumes:
      - ./data:/example_scenarios
    container_name: yako_vega
    restart: unless-stopped
    env_file:
      - .env
    command: bash -c "poetry run python3 main.py"