version: '2'
services:
  yako_vega:
    build:
      context: ./
    volumes:
      - ./data:/example_scenarios
      - ./app_logs:/logs/
    container_name: yako_vega
    restart: unless-stopped
    ports:
      - 8445:8445
    env_file:
      - .env
    command: bash -c "poetry run python3 main.py"